### ISSUE TITLE
DownloadTask.getLock()' on a null object reference

### ISSUE THREAD

**Issue by AndreyFetisov** [huxq17/Pump#34] opened 2020-07-19 13:18 UTC
Hi, what could be the reason for this error?

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.huxq17.download.core.task.DownloadTask.getLock()' on a null object reference
       at com.huxq17.download.core.interceptor.MergeFileInterceptor.intercept(MergeFileInterceptor.java:26)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
       at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:153)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
       at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
       at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
       at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
       at com.huxq17.download.core.task.Task.run(Task.java:23)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)

**Comment by huxq17** [comment] 2020-07-19 13:49
could you please describe the usage scenario?

**Comment by AndreyFetisov** [comment] 2020-07-19 14:15
Unfortunately, I am unable to reproduce this error on my device. This error is happening on my user.
When user click on the download button, the following code is executed:
Pump.newRequest(secUrl, filePath)
                .forceReDownload(true)
                .threadNum(2)
                .setId(map.mapId)
                .tag(myfile.fileName)
                .listener(downloadObserver)
                .setRetry(3, 200)
                .submit();

**Comment by huxq17** [comment] 2020-07-19 14:40
Which version you used that produce this error?

**Comment by AndreyFetisov** [comment] 2020-07-19 14:42
1.3.6

**Comment by huxq17** [comment] 2020-07-19 17:03
Are you sure the version of pump causing the problem is 1.3.6? After I reviewed the code, I felt unbelievable.  It looks like you have used old version of Pump. Can you provide Pump's version number when the error first occurred?

**Comment by AndreyFetisov** [comment] 2020-07-20 15:44
I can't say with 100% certainty, but I see this error in the Crashlytics logs.

**Comment by huxq17** [comment] 2020-07-20 17:10
How about I close this issue first, If this error still occurs at your new release apk that with Pump's lateset version,  we open this issue again?

**Comment by AndreyFetisov** [comment] 2020-07-20 17:14
Yes, I agree with you. Please, close this issue.

**Comment by huxq17** [comment] 2020-07-20 17:17
Ok,thank you.

**Comment by AndreyFetisov** [comment] 2020-07-26 16:19
Hi,

this issue persists in version 1.3.7.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.huxq17.download.core.task.DownloadTask.getLock()' on a null object reference
       at com.huxq17.download.core.interceptor.MergeFileInterceptor.intercept(MergeFileInterceptor.java:26)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
       at com.huxq17.download.core.interceptor.ConnectInterceptor.intercept(ConnectInterceptor.java:153)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
       at com.huxq17.download.core.interceptor.RetryInterceptor.intercept(RetryInterceptor.java:26)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:43)
       at com.huxq17.download.core.RealDownloadChain.proceed(RealDownloadChain.java:31)
       at com.huxq17.download.core.task.DownloadTask.downloadWithDownloadChain(DownloadTask.java:99)
       at com.huxq17.download.core.task.DownloadTask.execute(DownloadTask.java:85)
       at com.huxq17.download.core.task.Task.run(Task.java:23)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)

**Comment by huxq17** [comment] 2020-07-28 13:10
fixed at v1.3.8.

**Closed by huxq17** 2020-07-28 13:10 UTC
